#cloud-config

package_update: true
packages:
  - gnupg2
  - pass
  - gdb 


runcmd:
  - sleep 5
  - curl https://get.docker.com | sh
  - usermod -aG docker $USER
  - systemctl start docker
  - systemctl enable docker
  - curl -L "https://github.com/docker/compose/releases/download/1.28.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/bin/docker-compose
  - chmod +x /usr/bin/docker-compose
  - sleep 1
  
  - echo "----scaleway---"
  - mkfs.ext4 /dev/sda
  - mkfs.ext4 /dev/sdb
  - mkfs.ext4 /dev/sdc
  - mkdir /mnt/block
  - mkdir /mnt/block/mainnet
  - mkdir /mnt/block/testnet
  - mkdir /mnt/block/db
  - echo '/dev/sdb /mnt/block/mainnet ext4 defaults 0 0' >> /etc/fstab
  - echo '/dev/sda /mnt/block/testnet ext4 defaults 0 0' >> /etc/fstab
  - echo '/dev/sdc /mnt/block/testnet ext4 defaults 0 0' >> /etc/fstab
  - mount -o defaults /dev/sdb /mnt/block/mainnet
  - mount -o defaults /dev/sda /mnt/block/testnet
  - mount -o defaults /dev/sdc /mnt/block/db
  - chmod 777 -R /mnt/block

  - docker login ${docker_registry} --username ${docker_registry_username} --password ${docker_registry_password}
  - wget https://raw.githubusercontent.com/Microsoft/OMS-Agent-for-Linux/master/installer/scripts/onboard_agent.sh && sh onboard_agent.sh -w ${analytics_id} -s ${analytics_key}  -d opinsights.azure.com
  - /opt/microsoft/omsagent/bin/service_control restart ${analytics_id} 2>/dev/null 
  - docker-compose -f ${root_directory}/docker-compose.yml up -d
